$schema: "1.0"
name: devbox-customization
tasks:
  - name: winget
    parameters:
      package: Microsoft.PowerShell
  
  - name: winget
    parameters:
      package: OpenJS.NodeJS
  
  - name: winget
    parameters:
      package: Python.Python.3.11
  
  - name: install-docker
  
  - name: winget
    parameters:
      package: GitHub.GitHubDesktop
  
  - name: winget
    parameters:
      package: 7zip.7zip
  
  - name: winget
    parameters:
      package: Notepad++.Notepad++
  
  - name: winget
    parameters:
      package: Microsoft.VisualStudioCode
  
  - name: powershell
    parameters:
      command: |
        Invoke-WebRequest -Uri "https://github.com/microsoft/WSL/releases/download/2.3.24/wsl.2.3.24.0.arm64.msi" -OutFile "C:\temp\wsl.2.3.24.0.arm64.msi"
  
  - name: install-msi
    parameters:
      filePath: 'C:\temp\wsl.2.3.24.0.arm64.msi'

  - name: powershell
    parameters:
      command: |
        $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
        $username = $env:USERNAME
        Remove-LocalGroupMember -Group "Administrators" -Member $username
        Remove-Item -Path "C:\temp\" -Recurse -Force
      runAsUser: true
