$schema: "1.0"
name: devbox-customization
tasks:
  - name: winget
    parameters:
      package: Microsoft.PowerShell
  
  - name: winget
    parameters:
      package: OpenJS.NodeJS
  
  - name: winget
    parameters:
      package: Python.Python.3.11
  
  - name: winget
    parameters:
      package: GitHub.GitHubDesktop
  
  - name: winget
    parameters:
      package: 7zip.7zip
  
  - name: winget
    parameters:
      package: Notepad++.Notepad++
  
  - name: winget
    parameters:
      package: Microsoft.VisualStudioCode

  - name: install-docker
  
  - name: powershell
    parameters:
      command: |
        New-Item -Path "C:\temp" -ItemType Directory -Force
        #Invoke-WebRequest -Uri "https://github.com/microsoft/WSL/releases/download/2.3.24/wsl.2.3.24.0.arm64.msi" -OutFile "C:\temp\wsl.2.3.24.0.arm64.msi"
        #Invoke-WebRequest -Uri "https://desktop.docker.com/win/stable/Docker%20Desktop%20Installer.exe" -OutFile "C:\temp\DockerDesktopInstaller.exe"
        Invoke-WebRequest -Uri "https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi" -OutFile "C:\temp\wsl_update_x64.msi"
        
  #- name: install-msi
  #  parameters:
  #    filePath: 'C:\temp\wsl.2.3.24.0.arm64.msi'

  #- name: powershell
  #  parameters:
  #    command: |
  #      Start-Process "C:\temp\DockerDesktopInstaller.exe" -ArgumentList "--quiet", "--accept-license", "--backend=wsl-2", "--no-windows-containers" -Wait

  - name: git-clone
    description: 'Clone this repository into C:\src'
    parameters:
      repositoryUrl: https://github.com/CY2-Joe52189/devboxcentercatalog.git
      directory: C:\src

  - name: winget
    description: Apply a winget configuration file, downloading from a public URL to the specified path
    parameters:
      configurationFile: 'C:\src\devboxcentercatalog\CY2\winget-configurations\cy2-team-personalizations.dsc.yaml'
      runAsUser: true  
