$schema: "1.0"
name: devbox-customization
tasks:
  - name: winget
    parameters:
      package: Microsoft.PowerShell
  
  - name: winget
    parameters:
      package: Python.Python.3.11
  
  - name: winget
    parameters:
      package: GitHub.GitHubDesktop
  
  - name: winget
    parameters:
      package: 7zip.7zip
  
  - name: winget
    parameters:
      package: Notepad++.Notepad++
  
  - name: winget
    parameters:
      package: Microsoft.VisualStudioCode

  - name: winget
    parameters:
      package: GnuWin32.Make

  - name: winget
    parameters:
      package: Google.Chrome
  
  - name: choco
    description: install Node JS 20.18.0
    parameters:
      package: nodejs
      version: 20.17.0

  - name: choco
    description: install Docker Desktop
    parameters:
      package: docker-desktop

  - name: choco
    description: install PHP
    parameters:
      package: php 
      version: 8.3.13

  - name: choco
    description: install WSL2
    parameters:
      package: wsl2

  - name: winget
    parameters:
      downloadUrl: 'https://raw.githubusercontent.com/CY2-Joe52189/devboxcentercatalog/refs/heads/main/CY2/winget-configurations/cy2-team-personalizations.dsc.yaml'
      configurationFile: 'C:\winget-configurations/cy2-team-personalizations.dsc.yaml'
      runAsUser: true