$schema: "1.0"
name: devbox-customization
tasks:
  - name: winget
    parameters:
      package: Microsoft.PowerShell
  
  - name: winget
    parameters:
      package: OpenJS.NodeJS
  
  - name: winget
    parameters:
      package: Python.Python.3.11
  
  - name: winget
    parameters:
      package: GitHub.GitHubDesktop
  
  - name: winget
    parameters:
      package: 7zip.7zip
  
  - name: winget
    parameters:
      package: Notepad++.Notepad++
  
  - name: winget
    parameters:
      package: Microsoft.VisualStudioCode

  - name: install-docker
  
  - name: powershell
    parameters:
      command: |
        New-Item -Path "C:\temp" -ItemType Directory -Force
        Invoke-WebRequest -Uri "https://wslstorestorage.blob.core.windows.net/wslblob/wsl_update_x64.msi" -OutFile "C:\temp\wsl_update_x64.msi"

  - name: git-clone
    description: 'Clone this repository into C:\src'
    parameters:
      repositoryUrl: https://github.com/CY2-Joe52189/devboxcentercatalog.git
      directory: C:\src
  
  - name: powershell
    parameters:
      command: |
        # Copies docker admin settings config file over
        Copy-Item -Path "C:\src\devboxcentercatalog\cy2\admin-settings.json" -Destination "C:\ProgramData\DockerDesktop\" -Force
  
  - name: winget
    description: Apply a winget configuration file, downloading from a public URL to the specified path
    parameters:
      configurationFile: 'C:\src\devboxcentercatalog\CY2\winget-configurations\cy2-team-personalizations.dsc.yaml'
      runAsUser: true  
